name: Android CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 with the required distribution
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Specify the Java distribution (temurin, zulu, etc.)

      # Install Android SDK and create emulator
      - name: Setup Android Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"
          echo "no" | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel
          $HOME/android-sdk/emulator/emulator -avd test -no-window -no-audio &

      # Wait for the emulator to boot
      - name: Wait for Emulator
        run: adb wait-for-device

      # Run tests
      - name: Run tests
        run: ./gradlew connectedAndroidTest

      # Stop the emulator
      - name: Stop Emulator
        run: adb -s emulator-5554 emu kill
